---@class TestTableArrayTemplate 
---@field  Id int32 @英雄ID 
---@field  Weapons int32[] @武器(武器Id) 
---@field  born_position Position3d @出生位置 
---@field  TestTypes TestType_[] @测试类型 
---@field  LinkId int32 @ 
---@field  ModeL string @切片 
---@field  Icon string @Icon 
---@field  MachineTypes string[] @机体类型 
---@field  MapType string @地形适应 