// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Config
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TestObj_ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TestObj_ GetRootAsTestObj_(ByteBuffer _bb) { return GetRootAsTestObj_(_bb, new TestObj_()); }
  public static TestObj_ GetRootAsTestObj_(ByteBuffer _bb, TestObj_ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestObj_ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int A { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float B { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool C { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Config.TestObj_> CreateTestObj_(FlatBufferBuilder builder,
      int a = 0,
      float b = 0.0f,
      bool c = false) {
    builder.StartTable(3);
    TestObj_.AddB(builder, b);
    TestObj_.AddA(builder, a);
    TestObj_.AddC(builder, c);
    return TestObj_.EndTestObj_(builder);
  }

  public static void StartTestObj_(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddA(FlatBufferBuilder builder, int a) { builder.AddInt(0, a, 0); }
  public static void AddB(FlatBufferBuilder builder, float b) { builder.AddFloat(1, b, 0.0f); }
  public static void AddC(FlatBufferBuilder builder, bool c) { builder.AddBool(2, c, false); }
  public static Offset<Config.TestObj_> EndTestObj_(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Config.TestObj_>(o);
  }
};


}
