// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Config
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TestTableArraysTemplate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TestTableArraysTemplate GetRootAsTestTableArraysTemplate(ByteBuffer _bb) { return GetRootAsTestTableArraysTemplate(_bb, new TestTableArraysTemplate()); }
  public static TestTableArraysTemplate GetRootAsTestTableArraysTemplate(ByteBuffer _bb, TestTableArraysTemplate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestTableArraysTemplate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Weapons(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int WeaponsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetWeaponsBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetWeaponsBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetWeaponsArray() { return __p.__vector_as_array<int>(6); }
  public string Model { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetModelBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetModelBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetModelArray() { return __p.__vector_as_array<byte>(8); }
  public string Icon { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(10); }
  public string MachineType { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMachineTypeBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetMachineTypeBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetMachineTypeArray() { return __p.__vector_as_array<byte>(12); }
  public string MapType { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMapTypeBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetMapTypeBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetMapTypeArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<Config.TestTableArraysTemplate> CreateTestTableArraysTemplate(FlatBufferBuilder builder,
      int id = 0,
      VectorOffset weaponsOffset = default(VectorOffset),
      StringOffset modelOffset = default(StringOffset),
      StringOffset iconOffset = default(StringOffset),
      StringOffset machine_typeOffset = default(StringOffset),
      StringOffset map_typeOffset = default(StringOffset)) {
    builder.StartTable(6);
    TestTableArraysTemplate.AddMapType(builder, map_typeOffset);
    TestTableArraysTemplate.AddMachineType(builder, machine_typeOffset);
    TestTableArraysTemplate.AddIcon(builder, iconOffset);
    TestTableArraysTemplate.AddModel(builder, modelOffset);
    TestTableArraysTemplate.AddWeapons(builder, weaponsOffset);
    TestTableArraysTemplate.AddId(builder, id);
    return TestTableArraysTemplate.EndTestTableArraysTemplate(builder);
  }

  public static void StartTestTableArraysTemplate(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddWeapons(FlatBufferBuilder builder, VectorOffset weaponsOffset) { builder.AddOffset(1, weaponsOffset.Value, 0); }
  public static VectorOffset CreateWeaponsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateWeaponsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartWeaponsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddModel(FlatBufferBuilder builder, StringOffset modelOffset) { builder.AddOffset(2, modelOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(3, iconOffset.Value, 0); }
  public static void AddMachineType(FlatBufferBuilder builder, StringOffset machineTypeOffset) { builder.AddOffset(4, machineTypeOffset.Value, 0); }
  public static void AddMapType(FlatBufferBuilder builder, StringOffset mapTypeOffset) { builder.AddOffset(5, mapTypeOffset.Value, 0); }
  public static Offset<Config.TestTableArraysTemplate> EndTestTableArraysTemplate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Config.TestTableArraysTemplate>(o);
  }
};

public struct TestTableArraysTemplateList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TestTableArraysTemplateList GetRootAsTestTableArraysTemplateList(ByteBuffer _bb) { return GetRootAsTestTableArraysTemplateList(_bb, new TestTableArraysTemplateList()); }
  public static TestTableArraysTemplateList GetRootAsTestTableArraysTemplateList(ByteBuffer _bb, TestTableArraysTemplateList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestTableArraysTemplateList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Config.TestTableArraysTemplate? TestTableArrays(int j) { int o = __p.__offset(4); return o != 0 ? (Config.TestTableArraysTemplate?)(new Config.TestTableArraysTemplate()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TestTableArraysLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Config.TestTableArraysTemplateList> CreateTestTableArraysTemplateList(FlatBufferBuilder builder,
      VectorOffset test_table_arraysOffset = default(VectorOffset)) {
    builder.StartTable(1);
    TestTableArraysTemplateList.AddTestTableArrays(builder, test_table_arraysOffset);
    return TestTableArraysTemplateList.EndTestTableArraysTemplateList(builder);
  }

  public static void StartTestTableArraysTemplateList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTestTableArrays(FlatBufferBuilder builder, VectorOffset testTableArraysOffset) { builder.AddOffset(0, testTableArraysOffset.Value, 0); }
  public static VectorOffset CreateTestTableArraysVector(FlatBufferBuilder builder, Offset<Config.TestTableArraysTemplate>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTestTableArraysVectorBlock(FlatBufferBuilder builder, Offset<Config.TestTableArraysTemplate>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTestTableArraysVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Config.TestTableArraysTemplateList> EndTestTableArraysTemplateList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Config.TestTableArraysTemplateList>(o);
  }
  public static void FinishTestTableArraysTemplateListBuffer(FlatBufferBuilder builder, Offset<Config.TestTableArraysTemplateList> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedTestTableArraysTemplateListBuffer(FlatBufferBuilder builder, Offset<Config.TestTableArraysTemplateList> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
