//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config
{
    
    
    public class DailyTasksTemplate : IGenerateObject
    {
        
        /// <summary>
        /// 任务ID
        /// <summary>
        public int Id { get; private set; }
        
        /// <summary>
        /// 任务种类
        /// <summary>
        public int Kind { get; private set; }
        
        /// <summary>
        /// 酒馆等级区间
        /// <summary>
        public LevelRange_ LevelRange { get; private set; }
        
        /// <summary>
        /// 任务品质
        /// <summary>
        public int Quality { get; private set; }
        
        /// <summary>
        /// 需求玩家等级
        /// <summary>
        public int Level { get; private set; }
        
        /// <summary>
        /// 进度显示
        /// <summary>
        public int ShowProgress { get; private set; }
        
        /// <summary>
        /// 跳转
        /// <summary>
        public int AccessId { get; private set; }
        
        /// <summary>
        /// 任务信息
        /// <summary>
        public TaskInfo_ TaskInfo { get; private set; }
        
        /// <summary>
        /// 任务奖励
        /// <summary>
        public Reward_[] Rewards { get; private set; }
        
        /// <summary>
        /// 奖励展示
        /// <summary>
        public ShowReward_[] ShowRewards { get; private set; }
        
        public void Read(IConfigElement element)
        {
            this.Id = GeneratorUtility.Get(element, "Id",this.Id);
            this.Kind = GeneratorUtility.Get(element, "Kind",this.Kind);
            this.LevelRange = GeneratorUtility.Get(element, "LevelRange",this.LevelRange);
            this.Quality = GeneratorUtility.Get(element, "Quality",this.Quality);
            this.Level = GeneratorUtility.Get(element, "Level",this.Level);
            this.ShowProgress = GeneratorUtility.Get(element, "ShowProgress",this.ShowProgress);
            this.AccessId = GeneratorUtility.Get(element, "AccessId",this.AccessId);
            this.TaskInfo = GeneratorUtility.Get(element, "TaskInfo",this.TaskInfo);
            this.Rewards = GeneratorUtility.Get(element, "Rewards",this.Rewards);
            this.ShowRewards = GeneratorUtility.Get(element, "ShowRewards",this.ShowRewards);
            this.OnInit();
        }
        
        /// <summary>
        /// Init Function
        /// <summary>
        public virtual void OnInit()
        {
        }
        
        public static DailyTasksTemplate[] Load()
        {
            return Load<DailyTasksTemplate>();
        }
        
        public static T[] Load<T>()
            where T : DailyTasksTemplate, new ()
        {
            return GeneratorUtility.Load<T>("DailyTasksTemplate","DailyTask");
        }
        
        // 酒馆等级区间
        public sealed class LevelRange_ : IGenerateObject
        {
            
            public int Min { get; private set; }
            
            public int Max { get; private set; }
            
            public void Read(IConfigElement element)
            {
                this.Min = GeneratorUtility.Get(element, "Min",this.Min);
                this.Max = GeneratorUtility.Get(element, "Max",this.Max);
            }
        }
        
        // 任务信息
        public sealed class TaskInfo_ : IGenerateObject
        {
            
            public int Type { get; private set; }
            
            public int Param1 { get; private set; }
            
            public int Param2 { get; private set; }
            
            public int Param3 { get; private set; }
            
            public void Read(IConfigElement element)
            {
                this.Type = GeneratorUtility.Get(element, "Type",this.Type);
                this.Param1 = GeneratorUtility.Get(element, "Param1",this.Param1);
                this.Param2 = GeneratorUtility.Get(element, "Param2",this.Param2);
                this.Param3 = GeneratorUtility.Get(element, "Param3",this.Param3);
            }
        }
        
        public sealed class Reward_ : IGenerateObject
        {
            
            public int Type { get; private set; }
            
            public int Id { get; private set; }
            
            public int Count { get; private set; }
            
            public int Param1 { get; private set; }
            
            public void Read(IConfigElement element)
            {
                this.Type = GeneratorUtility.Get(element, "Type",this.Type);
                this.Id = GeneratorUtility.Get(element, "Id",this.Id);
                this.Count = GeneratorUtility.Get(element, "Count",this.Count);
                this.Param1 = GeneratorUtility.Get(element, "Param1",this.Param1);
            }
        }
        
        public sealed class ShowReward_ : IGenerateObject
        {
            
            public int Type { get; private set; }
            
            public int Id { get; private set; }
            
            public int Count { get; private set; }
            
            public void Read(IConfigElement element)
            {
                this.Type = GeneratorUtility.Get(element, "Type",this.Type);
                this.Id = GeneratorUtility.Get(element, "Id",this.Id);
                this.Count = GeneratorUtility.Get(element, "Count",this.Count);
            }
        }
    }
}
