# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/TestGlobal2Template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/TestGlobal2Template.proto',
  package='Config',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n protos/TestGlobal2Template.proto\x12\x06\x43onfig\"(\n\x13TestGlobal2Template\x12\x11\n\tTestFloat\x18\x01 \x01(\x02\x62\x06proto3'
)




_TESTGLOBAL2TEMPLATE = _descriptor.Descriptor(
  name='TestGlobal2Template',
  full_name='Config.TestGlobal2Template',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TestFloat', full_name='Config.TestGlobal2Template.TestFloat', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['TestGlobal2Template'] = _TESTGLOBAL2TEMPLATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestGlobal2Template = _reflection.GeneratedProtocolMessageType('TestGlobal2Template', (_message.Message,), {
  'DESCRIPTOR' : _TESTGLOBAL2TEMPLATE,
  '__module__' : 'protos.TestGlobal2Template_pb2'
  # @@protoc_insertion_point(class_scope:Config.TestGlobal2Template)
  })
_sym_db.RegisterMessage(TestGlobal2Template)


# @@protoc_insertion_point(module_scope)
