// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/TestGlobal2Template.proto

#include "protos/TestGlobal2Template.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Config {
class TestGlobal2TemplateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TestGlobal2Template> _instance;
} _TestGlobal2Template_default_instance_;
}  // namespace Config
static void InitDefaultsscc_info_TestGlobal2Template_protos_2fTestGlobal2Template_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Config::_TestGlobal2Template_default_instance_;
    new (ptr) ::Config::TestGlobal2Template();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TestGlobal2Template_protos_2fTestGlobal2Template_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TestGlobal2Template_protos_2fTestGlobal2Template_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_protos_2fTestGlobal2Template_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_protos_2fTestGlobal2Template_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_protos_2fTestGlobal2Template_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protos_2fTestGlobal2Template_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Config::TestGlobal2Template, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Config::TestGlobal2Template, testfloat_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Config::TestGlobal2Template)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Config::_TestGlobal2Template_default_instance_),
};

const char descriptor_table_protodef_protos_2fTestGlobal2Template_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n protos/TestGlobal2Template.proto\022\006Conf"
  "ig\"(\n\023TestGlobal2Template\022\021\n\tTestFloat\030\001"
  " \001(\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protos_2fTestGlobal2Template_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_protos_2fTestGlobal2Template_2eproto_sccs[1] = {
  &scc_info_TestGlobal2Template_protos_2fTestGlobal2Template_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protos_2fTestGlobal2Template_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2fTestGlobal2Template_2eproto = {
  false, false, descriptor_table_protodef_protos_2fTestGlobal2Template_2eproto, "protos/TestGlobal2Template.proto", 92,
  &descriptor_table_protos_2fTestGlobal2Template_2eproto_once, descriptor_table_protos_2fTestGlobal2Template_2eproto_sccs, descriptor_table_protos_2fTestGlobal2Template_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_protos_2fTestGlobal2Template_2eproto::offsets,
  file_level_metadata_protos_2fTestGlobal2Template_2eproto, 1, file_level_enum_descriptors_protos_2fTestGlobal2Template_2eproto, file_level_service_descriptors_protos_2fTestGlobal2Template_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protos_2fTestGlobal2Template_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_protos_2fTestGlobal2Template_2eproto)), true);
namespace Config {

// ===================================================================

class TestGlobal2Template::_Internal {
 public:
};

TestGlobal2Template::TestGlobal2Template(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Config.TestGlobal2Template)
}
TestGlobal2Template::TestGlobal2Template(const TestGlobal2Template& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  testfloat_ = from.testfloat_;
  // @@protoc_insertion_point(copy_constructor:Config.TestGlobal2Template)
}

void TestGlobal2Template::SharedCtor() {
  testfloat_ = 0;
}

TestGlobal2Template::~TestGlobal2Template() {
  // @@protoc_insertion_point(destructor:Config.TestGlobal2Template)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TestGlobal2Template::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void TestGlobal2Template::ArenaDtor(void* object) {
  TestGlobal2Template* _this = reinterpret_cast< TestGlobal2Template* >(object);
  (void)_this;
}
void TestGlobal2Template::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TestGlobal2Template::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TestGlobal2Template& TestGlobal2Template::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TestGlobal2Template_protos_2fTestGlobal2Template_2eproto.base);
  return *internal_default_instance();
}


void TestGlobal2Template::Clear() {
// @@protoc_insertion_point(message_clear_start:Config.TestGlobal2Template)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  testfloat_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestGlobal2Template::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float TestFloat = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          testfloat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TestGlobal2Template::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Config.TestGlobal2Template)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float TestFloat = 1;
  if (!(this->testfloat() <= 0 && this->testfloat() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_testfloat(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Config.TestGlobal2Template)
  return target;
}

size_t TestGlobal2Template::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Config.TestGlobal2Template)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float TestFloat = 1;
  if (!(this->testfloat() <= 0 && this->testfloat() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TestGlobal2Template::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Config.TestGlobal2Template)
  GOOGLE_DCHECK_NE(&from, this);
  const TestGlobal2Template* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TestGlobal2Template>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Config.TestGlobal2Template)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Config.TestGlobal2Template)
    MergeFrom(*source);
  }
}

void TestGlobal2Template::MergeFrom(const TestGlobal2Template& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Config.TestGlobal2Template)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.testfloat() <= 0 && from.testfloat() >= 0)) {
    _internal_set_testfloat(from._internal_testfloat());
  }
}

void TestGlobal2Template::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Config.TestGlobal2Template)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGlobal2Template::CopyFrom(const TestGlobal2Template& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Config.TestGlobal2Template)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGlobal2Template::IsInitialized() const {
  return true;
}

void TestGlobal2Template::InternalSwap(TestGlobal2Template* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(testfloat_, other->testfloat_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestGlobal2Template::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Config
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Config::TestGlobal2Template* Arena::CreateMaybeMessage< ::Config::TestGlobal2Template >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Config::TestGlobal2Template >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
